//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ContactsManagerInMVCLinqEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class State
    {
        public State()
        {
            this.AddressBooks = new HashSet<AddressBook>();
        }
    
        public int PKStateId { get; set; }
        public int FKCountryId { get; set; }
        public string StateName { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<AddressBook> AddressBooks { get; set; }
        public virtual Country Country { get; set; }
    }
}
